sudo: required
services:
- docker
language: node_js
node_js:
- 12
env:
  global:
  - DOCKER_USERNAME=cytomineulg
  - secure: "o9f2QDlZ9idUpBvlJY7QhYvHVyZsXEPE+dGOhlc3ezuVvOMB1EBsaugaABb4A4axiSmxsz9lv9y4seuYTbVD69d7F1cp4yibZxp+Tn4B7e//o2a72xTQPXldKE71Djm2sLPLVV95/1SjOOej75TVayxVeKJVmg9abjuNjB26PCm9Gh5Ggg5Ct2tHRqphzABmoCM3/LOAFQo4YtIMXRfQGPtHwhxt/qWheUJbeM5HoUyUnIhzRvPSqB+8pPPVDF3GqH6JZhimPzdsESnbrJTJnQDIfCz+qSpnhYJO5yk6ylaRxA8RLghOEnf2QliK1y7JO5KP2TCBYm+Kcg5Arys6TI6RtUwjxZ4KoOUbqAyk3gZCO7cUEINkfVSHQECpMhZXcGVbbOxB/oYsVKitNRfLQYt1AOuTmqeSwQxdhnW1B2jqmY/J0u01rHTxSMj6Qwp9jKZrerFhh2rH3E9+x5rGamo4gaIYDTC9U0FzYS2jADWJfvPBm58mm/JvJBaAk5xUVC922i7UEdRLRdp5L2t0j3/pcwG2lVNpU9huggYKIhhTWOexlkQIYrsBU4BOMqQDsQUhz75e6dPm5QSHNDIjaEI0HtB6QYeKRDnK3JASa8IAGRahcRDzOisryHpXc6mLpfJRNY6RnbIciWjAEAO3Ud12FIADKgDzVNTbDWh6nNc="
script:
- echo "Skip tests"
after_success:
- npm pack
- git fetch --tags
- |
  export VERSION=$(sed -nE 's/^\s*"version": "(.*?)",$/\1/p' package.json);
  export DEPLOY=false;
  if [[ ! $(git tag -l v$VERSION) ]]; then
    git config --local user.name "$(git log -1 --pretty=format:'%an')";
    git config --local user.email "$(git log -1 --pretty=format:'%ae')";
    git tag "v$VERSION";
    export DEPLOY=true;
    echo "Deploy with version $VERSION";
    docker build -f docker/Dockerfile -t cytomineuliege/web-ui:v$VERSION .;
  fi;
deploy:
  - provider: script
    script: >
      echo $VERSION &&
      docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" &&
      docker push cytomineuliege/web-ui:v$VERSION &&
      echo "Done."
    skip_cleanup: true
    on:
      condition: $DEPLOY = true
  - provider: releases
    edge: true
    api_key:
      secure: v6iaN/oL+rDe06b7LegdOJtvm/mcNLeh4i7S+UXtBauZWGt4lhR8FqLP3qKqRaHyS31cOi2rHtl60FZFfpyp88rmsDYdAgybL05b6WolBp/T+dW5rauADz2A0Yb3CurEOjWgrvCw2DIzg+SEOaNVAVq7ue6hXomfsEoyNHyTr/cChwgyXUmg2RAFV/w9ftucANofZUku7cxDmxpKdev38Y+9vN5D4cqdwoPRBxnXiU56lXa4xv4AHu/XdHCmcSDYpRlVTypPsI2LshPltmXatvhOhF0aGCWGfcSqZ4g0Wn3jfv2+rHSePn/tgJ23MHSN6uaEYjCK0bZB8q5FLqZ2BnaWwiFssYw4NWyszlyuvzJSo97PV9n8hUk6Q6i5XXYVcAskTP5E+9LdMf0gEpfXSjd0hFKggM9IQIxQYhCcnHTgrpSgezrqLZJDuRoknVKGcdTn58MwIqJ2TxlmfNYINxp1BlAsMqGBV5vHtAG1L1F+o4Sfw6EEQhZT37r+K6ye6kZ6iXNDw+ufPdKPmo9TdpL55klP0MWWJhqcBgy8y8ydkd9iZwfYvZbHyxk5PplgrYEJphJ6uksgwfcKTAb/eFEhATp7vs5NLpPMZhRuNmMUj+ucu+NrtfrLN5yM+XNsuRAXESCBHTf30PLOUvb9pMyZ+kvDPMY/pkxp2AY1qvU=
    file: "*.{tgz}"
    skip_cleanup: true
    on:
      condition: $DEPLOY = true
